import 'package:firebase_database/firebase_database.dart';
import '../models/chat_model.dart';
import '../models/game_types.dart';

class ChatService {
  final _db = FirebaseDatabase.instance;

  // 메시지 전송 (Direct Write)
  Future<void> sendMessage({
    required String roomId,
    required String uid,
    required String nickname,
    required String message,
    required ChatType type,
    TeamRole? team,
  }) async {
    final ref = _db.ref('chat_messages/$roomId');
    final newMessage = ChatMessage(
      id: '', // Generated by push()
      senderId: uid,
      senderName: nickname,
      content: message,
      timestamp: DateTime.now(),
      type: type,
      team: team,
    );

    await ref.push().set(newMessage.toJson());
  }

  // 메시지 스트림 (Direct Read)
  Stream<List<ChatMessage>> getMessagesStream(String roomId) {
    final ref = _db.ref('chat_messages/$roomId').orderByChild('timestamp');

    return ref.onValue
        .map((event) {
          if (event.snapshot.value == null) return <ChatMessage>[];

          final data = Map<dynamic, dynamic>.from(event.snapshot.value as Map);
          final messages = <ChatMessage>[];

          data.forEach((key, value) {
            final map = Map<dynamic, dynamic>.from(value as Map);
            messages.add(ChatMessage.fromMap(key, map));
          });

          // 시간순 정렬
          messages.sort((a, b) => a.timestamp.compareTo(b.timestamp));
          return messages;
        })
        .handleError((error) {
          // Permission denied might happen if game ends
          return <ChatMessage>[];
        });
  }
}
